"""create deployments and turnstile_sessions

Revision ID: 11b06407f645
Revises: 5536e5f07c1d
Create Date: 2026-06-03 14:31:09.584628
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '11b06407f645'
down_revision: Union[str, None] = '5536e5f07c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ingest_key_hash', sa.String(length=64), nullable=False),
    sa.Column('ingest_key_prefix', sa.String(length=16), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_ingest_key_hash'), 'deployments', ['ingest_key_hash'], unique=True)
    op.create_index(op.f('ix_deployments_organization_id'), 'deployments', ['organization_id'], unique=False)
    op.create_table('turnstile_sessions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('session_key', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('user_label', sa.String(length=255), nullable=True),
    sa.Column('key_fp', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('requests', sa.BigInteger(), nullable=False),
    sa.Column('prompt_tokens', sa.BigInteger(), nullable=False),
    sa.Column('completion_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('blocks', sa.BigInteger(), nullable=False),
    sa.Column('prevented', sa.Float(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deployment_id', 'session_key', name='uq_turnstile_session')
    )
    op.create_index(op.f('ix_turnstile_sessions_deployment_id'), 'turnstile_sessions', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_turnstile_sessions_organization_id'), 'turnstile_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_turnstile_sessions_session_key'), 'turnstile_sessions', ['session_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turnstile_sessions_session_key'), table_name='turnstile_sessions')
    op.drop_index(op.f('ix_turnstile_sessions_organization_id'), table_name='turnstile_sessions')
    op.drop_index(op.f('ix_turnstile_sessions_deployment_id'), table_name='turnstile_sessions')
    op.drop_table('turnstile_sessions')
    op.drop_index(op.f('ix_deployments_organization_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_ingest_key_hash'), table_name='deployments')
    op.drop_table('deployments')
    # ### end Alembic commands ###
