"""create projects link deployments and sessions

Revision ID: f47fd39658ef
Revises: 11b06407f645
Create Date: 2026-06-03 17:42:46.518199
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f47fd39658ef'
down_revision: Union[str, None] = '11b06407f645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.add_column('deployments', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_deployments_project_id'), 'deployments', ['project_id'], unique=False)
    op.create_foreign_key(None, 'deployments', 'projects', ['project_id'], ['id'])
    op.add_column('turnstile_sessions', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_turnstile_sessions_project_id'), 'turnstile_sessions', ['project_id'], unique=False)
    op.create_foreign_key(None, 'turnstile_sessions', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'turnstile_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_turnstile_sessions_project_id'), table_name='turnstile_sessions')
    op.drop_column('turnstile_sessions', 'project_id')
    op.drop_constraint(None, 'deployments', type_='foreignkey')
    op.drop_index(op.f('ix_deployments_project_id'), table_name='deployments')
    op.drop_column('deployments', 'project_id')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
